### ISSUE TITLE
Update Assembly Schema To Populate Status::State

### ISSUE THREAD

**Issue by santoshpuranik** [ibm-openbmc/bmcweb#247]
Similar to how we look at Operational Status to set the Status::Health Redfish property (See https://github.com/ibm-openbmc/bmcweb/pull/202), we can look at the Present property on D-Bus to set the Status::State property

If Present is true, set Status::State to Enabled, else set it to Absent.

**Comment by gtmills** [comment]
I opened https://github.com/ibm-openbmc/dev/issues/3476 so could mark as Ready For Dev
