### ISSUE TITLE
Need LocationIndicatorActive defined for fabric adapters

### ISSUE THREAD

**Issue by jinuthomas** [ibm-openbmc/bmcweb#400]
Need LocationIndicatorActive as an OEM property for the fabric adapters.

**Comment by lxwinspur** [comment]
review by: https://github.com/ibm-openbmc/bmcweb/pull/401

**Comment by lxwinspur** [comment]
@jinuthomas @mzipse @gtmills 

https://github.com/ibm-openbmc/bmcweb/pull/401

Looks like this patch has been around for a long time, so Could you please take a look at this patch? thanks

**Comment by gtmills** [comment]
Frank did this here: https://github.com/ibm-openbmc/bmcweb/pull/454
Closing
