### ISSUE TITLE
Failed to get FiremwareVersion property via `redfish/v1/Chassis/chassis`

### ISSUE THREAD

**Issue by lxwinspur** [ibm-openbmc/bmcweb#506]
Unable to get FiremwareVersion attribute using `redfish/v1/Chassis/chassis` command.
Because when the GetSubTree method is called, the interface parameter passed in is *xyz.openbmc_project.Inventory.Item.Chassis*, so the service name that can only be obtained is xzy.openbmc_project.Inventory.Manager, but there is no *xyz.openbmc_project.Software.Version* interface here, so this judgment will never enter.

https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L416-L454

**Comment by lxwinspur** [comment]
@gtmills @mzipse @patelabhishek9893 
Could you please check this issue again?
Thanks

**Comment by gtmills** [comment]
@lxwinspur So https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L446 is the Mex (IO expansion drawer) firmware version. 
It is OemChassis. 
The Firmware Version can be found at 
```
"FirmwareVersion": "fw1030.10-3-1030.2301.20230103a (NL1030_033)",  <--- This is the running firmware version
"Id": "bmc",
"LastResetTime": "2023-01-25T17:45:41+00:00",
"Links": {
"ActiveSoftwareImage": {
"@odata.id": ["/redfish/v1/UpdateService/FirmwareInventory/de045627"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/UpdateService/FirmwareInventory/de045627) <---- This is the running firmware Redfish object, query it for more information
},
"ManagerForChassis": [
{
"@odata.id": ["/redfish/v1/Chassis/chassis"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis)
}
],
"ManagerForChassis@odata.count": 1,
"ManagerForServers": [
{
"@odata.id": ["/redfish/v1/Systems/system"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/Systems/system)
}
],
"ManagerForServers@odata.count": 1,
"ManagerInChassis": {
"@odata.id": ["/redfish/v1/Chassis/chassis"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/Chassis/chassis)
},
"SoftwareImages": [
{
"@odata.id": ["/redfish/v1/UpdateService/FirmwareInventory/6b2712bd"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/UpdateService/FirmwareInventory/6b2712bd) <--- This is firmware images on the system, one is backup, one is primary 
}
},
{
"@odata.id": ["/redfish/v1/UpdateService/FirmwareInventory/de045627"](https://rain104bmc.aus.stglabs.ibm.com/redfish/v1/UpdateService/FirmwareInventory/de045627)  <--- This is firmware images on the system, one is backup, one is primary. Based on the ActiveSoftwareImage value above I know this one is the primary 
}
],
"
```

**Comment by gtmills** [comment]
I can see that the CEC chassis doesn't show up here:
```
dbus-send --system --print-reply --dest=xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper xyz.openbmc_project.ObjectMapper.GetSubTreePaths string:"/xyz/openbmc_project/inventory" int32:0 array:string:"xyz.openbmc_project.Software.Version"
method return time=1674762255.106138 sender=:1.25 -> destination=:1.45270 serial=284879 reply_serial=2
   array [
      string "/xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply0"
      string "/xyz/openbmc_project/inventory/system/chassis/motherboard/powersupply1"
   ]

```

So for the CEC chassis /redfish/v1/Chassis/chassis, should never enter this if
https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L418

**Comment by gtmills** [comment]
The only time, the code should enter that if (https://github.com/ibm-openbmc/bmcweb/blob/1020/redfish-core/lib/chassis.hpp#L418) is if PLDM has created a `xyz.openbmc_project.Software.Version` interface for the Mex chassis 

https://github.com/ibm-openbmc/pldm/commit/8ca3014a6d7de340c587f28f00f1c99cf3b746d2

**Comment by lxwinspur** [comment]
Oh, I see
Thanks @gtmills
